### ISSUE TITLE
? soacceptqueue errantly set to 128 ?

### ISSUE THREAD

**Issue by Aranjedeath** [libp2p/go-sockaddr#1]
This is an exploratory bug, because I don't know enough about go to answer this myself and file a better bug. I've been asked to file it on behalf of IPFS.

They, apparently, use go-sockaddr. 

As an IPFS user, I noticed that one of the TCP sockets bound with a 128 depth soacceptqueue. My operating system is freebsd, and as such has a kernel tunable kern.ipc.soacceptqueue. It's set to 4096, not 128. An IPFS person suggests this socket is bound or managed by go-sockaddr. 

Any idea why it would not respect my OS settings? Or perhaps I should bark up golang's tree?

**Comment by jbenet** [comment]
I borrowed directly from the golang source-- i dont think i changed that, but havent checked. look at the sources in golang-- we shouldn't be doing anything different here.

cc @whyrusleeping ??

**Comment by Stebalien** [comment]
This looks like https://github.com/golang/go/issues/11412 and I believe this has been fixed. Can you try again?

**Comment by Aranjedeath** [comment]
Can you spot the fix? When I wrote this bug it did not matter if you set somaxconn or soacceptqueue (both are in fact set), ipfs ignored them and set to 128. I can try it again and check, though.

**Comment by Stebalien** [comment]
@Aranjedeath nevermind; the fix isn't merged yet. The fix is [here](https://go-review.googlesource.com/c/go/+/64910/4/src/net/sock_bsd.go#22), FYI.

>  When I wrote this bug it did not matter if you set somaxconn or soacceptqueue

Then I'm not entirely sure this *will* fix it. It should have been using `somaxconn`.

**Comment by Stebalien** [comment]
As far as I can tell, this is a go-wide bug (all go code has this problem, from what I can tell) so I'm going to close this issue. If that's *not* the case, tell me and I'll look deeper.
