### ISSUE TITLE
GCC required for compilation

### ISSUE THREAD

**Issue by CsterKuroi** [libp2p/go-sockaddr#17]
When compiling the latest version of IPFS master branch on win10.

```
...
go: downloading github.com/marten-seemann/qtls v0.9.1
go: extracting golang.org/x/crypto v0.0.0-20200423211502-4bdfaf469ed5
go: extracting github.com/marten-seemann/qtls v0.9.1
# github.com/libp2p/go-sockaddr
exec: "gcc": executable file not found in %PATH%
```

**Comment by CsterKuroi** [comment]
After `choco install mingw`, build successfully.

**Comment by Stebalien** [comment]
Pass `CGO_ENABLED=0`? It will only build with CGO if enabled.

**Comment by CsterKuroi** [comment]
You're right.
IPFS v0.4.23 didn't import this library, so it blocked me for a while.

**Comment by Stebalien** [comment]
Yeah, this is enough of a trip-up that I'm going to just remove these functions. They aren't used anyways.
